online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop_app.urls")),
    path("", include("user_app.urls")),
    path("", include("orders_app.urls")),
]

online_store/orders_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("basket", views.Basket.as_view(), name="basket"),
    path("makeorder", views.MakeOrder.as_view(), name="make_order"),
    path(
        "makeorder/payment<int:pk>",
        views.MakeOrderPayment.as_view(),
        name="make_order_payment",
    ),
    path("lk/orderhistory", views.OrderHistory.as_view(), name="order_history"),
    path("lk/order<int:pk>", views.OrderPage.as_view(), name="order_page"),
    path(
        "catalog/product<int:pk>/modal_open",
        views.add_to_basket,
        name="product_page_modal",
    ),
    path("add_item", views.add_to_basket_catalog, name="catalog_page_modal"),
    path("delate<int:pk>", views.delete_from_basket, name="delete_from_basket"),
    path("remove_item_amount", views.remove_item_amount, name="remove_item_amount"),
    path("add_item_amount", views.add_item_amount, name="add_item_amount"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/shop_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.MainPage.as_view(), name="main"),
    path("catalog", views.Catalog.as_view(), name="catalog"),
    path("catalog/product<int:pk>", views.Product.as_view(), name="product_page"),
    path(
        "catalog/category<int:pk>", views.CategoryView.as_view(), name="category_page"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/orders_app/models.py
from django.db import models
from django.contrib.auth.models import User
from shop_app.models import Goods


class Purchase(models.Model):
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="товар")
    amount = models.IntegerField(verbose_name="количество")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="пользователь"
    )
    order = models.ForeignKey(
        "Order", on_delete=models.CASCADE, verbose_name="заказ", null=True, blank=True
    )

    class Meta:
        verbose_name_plural = "покупки"
        verbose_name = "покупка"

    def __str__(self):
        return f"{self.goods} куплено {self.user}"


class Order(models.Model):
    statuses = [("paid", "оплачен"), ("not_paid", "не оплачен")]
    payments = [("card", "Онлйан карта"), ("random_card", "Рандомная карта")]
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="пользователь"
    )
    delivery = models.ForeignKey(
        "Delivery",
        on_delete=models.SET_NULL,
        verbose_name="доставка",
        null=True,
        blank=True,
    )
    status = models.CharField(
        choices=statuses, max_length=30, default="not_paid", verbose_name="статус"
    )
    data = models.DateField(auto_now_add=True, verbose_name="дата заказа")
    cost = models.IntegerField(verbose_name="стоимость")
    payment_type = models.CharField(
        choices=payments,
        max_length=30,
        default="card",
        verbose_name="тип доставки",
        null=True,
        blank=True,
    )
    city = models.CharField(
        max_length=30, verbose_name="город доставки", null=True, blank=True
    )
    address = models.CharField(
        max_length=1000, verbose_name="адрес", null=True, blank=True
    )

    class Meta:
        verbose_name_plural = "заказы"
        verbose_name = "заказ"

    def __str__(self):
        return f"заказ {self.id} от {self.data} пользователя {self.user}"


class Delivery(models.Model):
    title = models.CharField(max_length=30, verbose_name="название вида доставки")
    price = models.IntegerField(verbose_name="стоимость доставки")

    class Meta:
        verbose_name_plural = "доставки"
        verbose_name = "доставка"

    def __str__(self):
        return self.title

online_store/orders_app/forms.py
from django.forms import ModelForm
from orders_app.models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ["user", "delivery", "cost", "payment_type", "city", "address"]

online_store/orders_app/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from orders_app.models import Order, Purchase, Delivery
from user_app.models import Profile
from shop_app.models import Goods
from copy import deepcopy
import random
from orders_app.forms import OrderForm


class Basket(ListView):
    model = Purchase
    template_name = "orders_app/busket.html"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Purchase.objects.select_related("goods").filter(
                user=self.request.user, order__isnull=True
            )
        else:
            return []

    def get_context_data(self, **kwargs):
        context = super(Basket, self).get_context_data(**kwargs)
        if not self.request.user.is_authenticated:
            if self.request.session.get("basket") == None:
                context["object_list"] = []
                context["sum"] = 0
            else:
                object_list = deepcopy(self.request.session["basket"])
                sum = 0
                for obj in object_list:
                    obj["goods"] = Goods.objects.get(id=obj["goods"])
                    sum += int(obj["amount"]) * obj["goods"].price
                context["object_list"] = object_list
                context["sum"] = sum
        else:
            item_list = list(context["object_list"])
            sum = 0
            for item in item_list:
                sum += item.amount * item.goods.price
            context["sum"] = sum
        return context


class MakeOrder(View):
    def get(self, request):
        delivery_costs = {
            "ord": Delivery.objects.get(title="Обычная").price,
            "exp": Delivery.objects.get(title="Экспресс").price,
        }
        if self.request.user.is_authenticated:
            basket_list = list(
                Purchase.objects.select_related("goods").filter(
                    user=request.user, order__isnull=True
                )
            )
            sum = 0
            for item in basket_list:
                sum += item.amount * item.goods.price
        else:
            basket_list = deepcopy(self.request.session["basket"])
            sum = 0
            for obj in basket_list:
                obj["goods"] = Goods.objects.get(id=obj["goods"])
                sum += obj["amount"] * obj["goods"].price

        if request.user.is_authenticated:
            profile = Profile.objects.get(user=request.user)
            return render(
                request,
                "orders_app/order_process.html",
                {
                    "profile": profile,
                    "basket_list": basket_list,
                    "sum": sum,
                    "delivery_costs": delivery_costs,
                },
            )

        return render(
            request,
            "orders_app/order_process.html",
            {"basket_list": basket_list, "sum": sum, "delivery_costs": delivery_costs},
        )

    def post(self, request):
        items_list = list(
            Purchase.objects.select_related("goods").filter(
                user=self.request.user, order__isnull=True
            )
        )
        delivery = request.POST.get("delivery")
        sum = 0
        for item in items_list:
            sum += item.amount * item.goods.price
        if delivery == "express":
            delivery = Delivery.objects.get(title="Экспресс")
            sum += delivery.price
        else:
            delivery = Delivery.objects.get(title="Обычная")
            if sum < 2000:
                sum += delivery.price
        payment_type = request.POST.get("pay")
        if payment_type == "online":
            payment_type = "card"
        else:
            payment_type = "random_card"
        city = request.POST.get("city")
        address = request.POST.get("address")

        order = OrderForm(
            {
                "delivery": delivery,
                "user": request.user,
                "cost": sum,
                "payment_type": payment_type,
                "city": city,
                "address": address,
            }
        )

        if order.is_valid():
            order.save()
        else:
            return HttpResponse(
                "Возникла ошибка, обновите сайт и попробуйте заполнить ланные заказа снова"
            )

        order = Order.objects.filter(user=request.user).latest("id")

        for item in items_list:
            item.order = order
            item.save(update_fields=["order"])
            item.goods.was_bought_times += item.amount
            item.goods.save(update_fields=["was_bought_times"])
        link_path = f"/makeorder/payment{order.id}"
        return HttpResponseRedirect(link_path)


class MakeOrderPayment(View):
    def get(self, request, pk):
        order = Order.objects.get(id=pk)
        if order.payment_type == "card":
            return render(request, "orders_app/payment.html")
        else:
            return render(request, "orders_app/payment_random.html")

    def post(self, request, pk):
        order = Order.objects.get(id=pk)
        cart_number = int(request.POST.get("numero1").split(" ")[1])
        error_list = [
            "Оплата не прошла. Недостаточно средств на карте.",
            "Оплата не прошла. Операция отклонена банком.",
            "Оплата не прошла. Некорректные данные карты.",
        ]
        if cart_number % 2 == 0 and cart_number % 10 != 0:
            result = "Оплата прошла успешно!"
            order.status = "paid"
            order.save(update_fields=["status"])
        else:
            result = random.choice(error_list)
        return render(request, "orders_app/pay_result.html", {"result": result})


class OrderHistory(ListView):
    model = Order
    template_name = "orders_app/order_history.html"

    def get_queryset(self):
        return (
            Order.objects.filter(user=self.request.user)
            .order_by("-id")
            .only("id", "data", "delivery", "status", "cost", "payment_type")
        )


class OrderPage(DetailView):
    model = Order
    template_name = "orders_app/order_page.html"

    def get_context_data(self, **kwargs):
        context = super(OrderPage, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        items_list = list(
            Purchase.objects.select_related("goods")
            .only("goods", "amount")
            .filter(order=self.object)
        )
        context["profile"] = profile
        context["items_list"] = items_list
        return context


def add_to_basket(request, pk):
    goods = Goods.objects.get(id=pk)
    if request.user.is_authenticated:
        basket_list = list(
            Purchase.objects.select_related("goods").filter(
                user=request.user, order__isnull=True
            )
        )
        add_to_basket_flag = True
        for obj in basket_list:
            if obj.goods == goods:
                obj.amount += int(request.POST.get("amount"))
                obj.save()
                add_to_basket_flag = False
                break
        if add_to_basket_flag:
            basket_item = Purchase(
                user=request.user, goods=goods, amount=request.POST.get("amount")
            )
            basket_item.save()
    else:
        if request.session.get("basket") is None:
            basket_list = [{"goods": goods.id, "amount": request.POST.get("amount")}]
        else:
            basket_list = request.session["basket"]
            add_to_basket_flag = True
            for item in basket_list:
                if item["goods"] == goods.id:
                    item["amount"] += int(request.POST.get("amount"))
                    add_to_basket_flag = False
                    break
            if add_to_basket_flag:
                basket_list.append(
                    {"goods": goods.id, "amount": request.POST.get("amount")}
                )
        request.session["basket"] = basket_list
        request.session.modified = True
    return HttpResponse(status=200)


def add_to_basket_catalog(request):
    goods = Goods.objects.get(id=request.POST.get("id"))
    if request.user.is_authenticated:
        basket_list = list(
            Purchase.objects.select_related("goods").filter(
                user=request.user, order__isnull=True
            )
        )
        add_to_basket_flag = True
        for obj in basket_list:
            if obj.goods == goods:
                obj.amount += 1
                obj.save()
                add_to_basket_flag = False
                break
        if add_to_basket_flag:
            basket_item = Purchase(user=request.user, goods=goods, amount=1)
            basket_item.save()
    else:
        if request.session.get("basket") is None:
            basket_list = [{"goods": goods.id, "amount": 1}]
        else:
            basket_list = request.session["basket"]
            add_to_basket_flag = True
            for item in basket_list:
                if item["goods"] == goods.id:
                    item["amount"] += 1
                    add_to_basket_flag = False
                    break
            if add_to_basket_flag:
                basket_list.append({"goods": goods.id, "amount": 1})
        request.session["basket"] = basket_list
        request.session.modified = True
    return HttpResponse(status=200)


def delete_from_basket(request, pk):
    if request.user.is_authenticated:
        item = Purchase.objects.get(id=pk)
        item.delete()
    else:
        basket_list = request.session["basket"]
        for item in basket_list:
            if item["goods"] == pk:
                basket_list.remove(item)
                break
        request.session.modified = True
    return HttpResponseRedirect("/basket")


def remove_item_amount(request):

online_store/orders_app/templates/orders_app/order_history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Навигация
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="/lk">Личный кабинет</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="/lk/edit">Профиль</a>
                                    </li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="/lk/orderhistory">История
                                        заказов</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Orders">
                        {% for object in object_list %}
                            <div class="Order Order_anons">
                                <div class="Order-personal">
                                    <div class="row">
                                        <div class="row-block"><a class="Order-title" href="/lk/order{{ object.id }}">Заказ&#32;<span
                                                class="Order-numberOrder">{{ object.id }}</span>&#32;от&#32;<span
                                                class="Order-dateOrder">{{ object.data|date:"d.m.Y" }}</span></a>
                                        </div>
                                        <div class="row-block">
                                            <div class="Order-info Order-info_delivery">
                                                <div class="Order-infoType">Тип доставки:
                                                </div>
                                                <div class="Order-infoContent">{{ object.delivery }}
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_pay">
                                                <div class="Order-infoType">Оплата:
                                                </div>
                                                <div class="Order-infoContent">{{ object.get_payment_type_display }}
                                                </div>
                                            </div>
                                            <div class="Order-info">
                                                <div class="Order-infoType">Общая стоимость:
                                                </div>
                                                <div class="Order-infoContent"><span
                                                        class="Order-price">{{ object.cost }} руб.</span>
                                                </div>
                                            </div>
                                            <div class="Order-info Order-info_status">
                                                <div class="Order-infoType">Статус:
                                                </div>
                                                <div class="Order-infoContent">{{ object.get_status_display }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

online_store/orders_app/templates/orders_app/order_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Заказ {{ object.id }}
                    </h1>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Orders">
                    </div>
                    <div class="Order">
                        <div class="Order-infoBlock">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block">
                                        <div class="Order-info Order-info_date">
                                            <div class="Order-infoType">Дата заказа:
                                            </div>
                                            <div class="Order-infoContent">{{ object.data|date:"d.m.Y" }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">ФИО:
                                            </div>
                                            <div class="Order-infoContent">{{ profile.name }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Телефон:
                                            </div>
                                            <div class="Order-infoContent">{{ profile.phone }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">E-mail:
                                            </div>
                                            <div class="Order-infoContent">{{ request.user.email }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">Тип доставки:
                                            </div>
                                            <div class="Order-infoContent">{{ object.delivery }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Город:
                                            </div>
                                            <div class="Order-infoContent">{{ object.city }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">Адрес:
                                            </div>
                                            <div class="Order-infoContent">{{ object.address }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">Оплата:
                                            </div>
                                            <div class="Order-infoContent">{{ object.get_payment_type_display }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">Статус:
                                            </div>
                                            <div class="Order-infoContent">{{ object.get_status_display }}
                                            </div>
                                        </div>
                                        {% if  object.status == 'not_paid' %}
                                        <div class="Order-info Order-info_error">
                                            <div class="Order-infoType">Оплата не прошла:
                                            </div>
                                            <div class="Order-infoContent">Оплата не выполнена
                                            </div>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="Cart Cart_order">
                                {% for item in items_list %}
                                    <div class="Cart-product">
                                        <div class="Cart-block Cart-block_row">
                                            <div class="Cart-block Cart-block_pict"><a class="Cart-pict"
                                                                                       href="/catalog/product{{ item.goods.id }}">
                                                {% if item.goods.Photo %}
                                                    <img class="Cart-img" src="{{ item.goods.Photo.url }}"
                                                         alt="card.jpg"/>
                                                {% else %}
                                                    <img class="Cart-img"
                                                         src="{% static 'assets/img/content/no_photo.png' %}"
                                                         alt="card.jpg"/>
                                                {% endif %}
                                            </a>
                                            </div>
                                            <div class="Cart-block Cart-block_info"><a class="Cart-title"
                                                                                       href="/catalog/product{{ item.goods.id }}">{{ item.goods.title }}</a>
                                                <div class="Cart-desc">{{ item.goods.short_info }}
                                                </div>
                                            </div>
                                            <div class="Cart-block Cart-block_price">
                                                <div class="Cart-price">{{ item.goods.price }} руб.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="Cart-block Cart-block_row">

                                            <div class="Cart-block Cart-block_amount">{{ item.amount }} шт.
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <div class="Cart-total">
                                    <div class="Cart-block Cart-block_total">
                                        <strong class="Cart-title">Итого:<span
                                                class="Cart-price">{{ object.cost }} руб.</span>
                                        </strong>
                                    </div>
                                    {% if  object.status == 'not_paid' %}
                                    <div class="Cart-block"><a class="btn btn_primary btn_lg" href="/makeorder/payment{{object.id}}">Оплатить</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

online_store/orders_app/templates/orders_app/pay_result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Оплата
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="/">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="ProgressPayment">
                    <div class="ProgressPayment-title">{{ result }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

online_store/orders_app/templates/orders_app/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Оплата
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="/">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <form class="form Payment" method="post">
                    {% csrf_token %}
                    <div class="Payment-card">
                        <div class="form-group">
                            <label class="form-label">Номер карты
                            </label>
                            <input class="form-input Payment-bill" id="numero1" name="numero1" type="text" placeholder="9999 9999" data-mask="9999 9999" data-validate="require pay" />
                        </div>
                    </div>
                    <div class="Payment-pay"><button class="btn btn_primary" type="submit">Оплатить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

online_store/orders_app/templates/orders_app/payment_random.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">Оплата
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="/">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <form class="form Payment" method="post">
                    {% csrf_token %}
                    <div class="Payment-card">
                        <div class="form-group">
                            <label class="form-label">Номер карты
                            </label>
                            <input class="form-input Payment-bill" id="numero1" name="numero1" type="text" placeholder="9999 9999" data-mask="9999 9999" data-validate="require pay" />
                        </div>
                        <div class="form-group"><a class="btn btn_success Payment-generate" href="#">Сгенирировать случайный счет</a>
                        </div>
                    </div>
                    <div class="Payment-pay"><button class="btn btn_primary" type="submit">Оплатить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}